#!/usr/bin/env php
<?php

chdir(dirname(__DIR__));

$loader = require_once 'vendor/autoload.php';

set_time_limit(0);


use Silex\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');

$app = new Application();
$cli = true;

require_once('app/bootstrap.php');

$console = require __DIR__.'/console.php';
$console->run();
